development:
  adapter: postgresql
  encoding: unicode
  database: real_estate_cms_development
  pool: 5
  host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: real_estate_cms_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: real_estate_cms_production
  pool: 5

cucumber:
  <<: *test