development:
  adapter: postgresql
  encoding: unicode
  database: real_estate_cms_development
  host: localhost
  min_messages: warning

test: &test
  adapter: postgresql
  encoding: unicode
  database: real_estate_cms_test
  host: localhost
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: real_estate_cms_production
  min_messages: warning

cucumber:
  <<: *test
